version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: propiedadesdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=rootpassword || exit 1"]
      interval: 30s  # Espera 30 segundos antes de la primera verificación
      timeout: 10s   # Espera 10 segundos para recibir respuesta antes de fallar
      retries: 10    # Intenta 10 veces antes de marcarlo como "unhealthy"
      start_period: 40s # Espera 40s antes de comenzar a hacer health checks

  spring-app:
    build: .
    container_name: spring_boot_container
    restart: always
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/propiedadesdb?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: adminpassword
    ports:
      - "8080:8080"

volumes:
  mysql_data:
